name: Collect Static Files

on:
  push:
    branches:
      - main

jobs:
  collect-static:
    runs-on: ubuntu-latest

    steps:
      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput
