# Generated by Django 5.0.4 on 2024-04-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_last_name', models.CharField(max_length=100)),
                ('person_age', models.IntegerField()),
            ],
        ),
    ]
